[package]
name = "atoy"
version = "0.1.0"
authors = ["MagicCrazyMan <350088648@qq.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]
rebind = []

[dependencies]
wasm-bindgen = { version = "0.2.89" }
gl-matrix4rust = { path = "../gl-matrix4rust", features = ["gl"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
web-sys = { version = "0.3.67", features = ["Performance", "Window", "Element", "HtmlElement", "Document", "HtmlCanvasElement", "WebGl2RenderingContext", "WebGlUniformLocation", "WebGlProgram", "WebGlShader", "WebGlBuffer", "WebGlFramebuffer", "WebGlActiveInfo", "CssStyleDeclaration", "WebGlVertexArrayObject", "WebGlTexture", "Headers", "Request", "RequestInit", "RequestMode", "Response", "HtmlImageElement", "ImageData", "HtmlVideoElement", "ImageBitmap", "Url", "Blob", "CanvasRenderingContext2d", "ResizeObserver", "ResizeObserverEntry", "WebGlRenderbuffer", "MouseEvent", "KeyboardEvent", "WheelEvent", "TouchEvent", "TouchList", "AddEventListenerOptions", "Touch", "WebGlSync", "WebglCompressedTextureS3tc", "WebglCompressedTextureEtc", "WebglCompressedTextureAtc", "WebglCompressedTextureEtc1", "WebglCompressedTextureAstc", "WebglCompressedTextureS3tcSrgb", "WebglCompressedTexturePvrtc", "WebglDebugRendererInfo", "WebglDebugShaders", "WebglLoseContext", "WebGlSampler", "ExtTextureFilterAnisotropic", "EventListenerOptions", "EventTarget", "FormData", "DomException"] }
wasm-bindgen-test = "0.3.38"
serde = { version = "1.0.192", features = ["derive"] }
serde-wasm-bindgen = "0.6.1"
uuid = { version = "1.5.0", features = ["v4", "fast-rng"] }
serde_json = "1.0.108"
rand = "0.8.5"
log = "0.4.20"
console_log = "1.0.0"
fern = "0.6.2"
wasm-bindgen-futures = "0.4.39"
hashbrown = "0.14.3"
indexmap = "2.1.0"
smallvec = "1.13.1"
js-sys = "0.3.67"
regex = "1.10.3"
async-trait = "0.1.80"
url = "2.5.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
opt-level = 3
