/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneController: typeof import('./src/components/SceneController.vue')['default']
    SceneDebugger: typeof import('./src/components/SceneDebugger.vue')['default']
    SceneViewer: typeof import('./src/components/SceneViewer.vue')['default']
  }
}
